name: flutter_analyze_and_test

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1.1.1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test --verbose --coverage --coverage-path=~/coverage/lcov.info
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ~/coverage/lcov.info
